%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: A:\Powertrain Opti\12_9_2022_025_postDOEresults.csv
%
% Auto-generated by MATLAB on 09-Dec-2022 00:05:30

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Intake", "Exhaust", "Points", "FinalDrive"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
postDOEresults = readtable("A:\Powertrain Opti\12_9_2022_025_postDOEresults.csv", opts);


%% Clear temporary variables
clear opts

%% plot
fig1 = figure;
scatter3(postDOEresults, "Intake","Exhaust","FinalDrive", "ColorVariable","Points")
fig2 = figure;
scatter3(postDOEresults, "Intake","Exhaust","Points", "ColorVariable","FinalDrive")